// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {git} from '../models';
import {ssh} from '../models';

export function ClosePane(arg1:string,arg2:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateProfileFolder(arg1:string):Promise<void>;

export function CreateSession(arg1:main.CreateSessionReq):Promise<Record<string, any>>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteProfileFolder(arg1:string):Promise<void>;

export function ExportSSH(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetDetectedProfiles():Promise<Array<config.Profile>>;

export function GetGitBranches(arg1:string):Promise<Array<git.GitBranch>>;

export function GetGitCommitDetail(arg1:string,arg2:string):Promise<git.GitCommitDetail>;

export function GetGitDiff(arg1:string,arg2:string):Promise<git.GitDiffResult>;

export function GetGitLog(arg1:string,arg2:number):Promise<Array<git.GitCommit>>;

export function GetGitRemotes(arg1:string):Promise<Array<git.GitRemote>>;

export function GetGitStatus(arg1:string):Promise<git.GitStatusResult>;

export function GetProfiles():Promise<Array<config.Profile>>;

export function GetSSHConfig():Promise<ssh.Config>;

export function GetServerPort():Promise<number>;

export function GetSessions():Promise<Array<any>>;

export function GitCheckout(arg1:string,arg2:string):Promise<git.GitOpResult>;

export function GitCommit(arg1:string,arg2:string):Promise<git.GitOpResult>;

export function GitFetch(arg1:string):Promise<git.GitOpResult>;

export function GitPull(arg1:string):Promise<git.GitOpResult>;

export function GitPush(arg1:string):Promise<git.GitOpResult>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<git.GitOpResult>;

export function GitStageAll(arg1:string):Promise<git.GitOpResult>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<git.GitOpResult>;

export function ImportSSH(arg1:string):Promise<void>;

export function KillServer():Promise<void>;

export function MoveProfile(arg1:string,arg2:string,arg3:number):Promise<void>;

export function OpenWorkFolder(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RenameProfileFolder(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ReorderProfileFolders(arg1:Array<string>):Promise<void>;

export function SaveGitPollInterval(arg1:number):Promise<void>;

export function SaveProfile(arg1:config.Profile):Promise<void>;

export function SaveSSHConfig(arg1:ssh.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SplitPane(arg1:main.SplitPaneReq):Promise<Record<string, any>>;
