// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePane(arg1, arg2) {
  return window['go']['main']['App']['ClosePane'](arg1, arg2);
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportSSH(arg1) {
  return window['go']['main']['App']['ExportSSH'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectedProfiles() {
  return window['go']['main']['App']['GetDetectedProfiles']();
}

export function GetGitBranches(arg1) {
  return window['go']['main']['App']['GetGitBranches'](arg1);
}

export function GetGitCommitDetail(arg1, arg2) {
  return window['go']['main']['App']['GetGitCommitDetail'](arg1, arg2);
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitLog(arg1, arg2) {
  return window['go']['main']['App']['GetGitLog'](arg1, arg2);
}

export function GetGitRemotes(arg1) {
  return window['go']['main']['App']['GetGitRemotes'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSSHConfig() {
  return window['go']['main']['App']['GetSSHConfig']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitCheckout'](arg1, arg2);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitFetch(arg1) {
  return window['go']['main']['App']['GitFetch'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function ImportSSH(arg1) {
  return window['go']['main']['App']['ImportSSH'](arg1);
}

export function KillServer() {
  return window['go']['main']['App']['KillServer']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SaveGitPollInterval(arg1) {
  return window['go']['main']['App']['SaveGitPollInterval'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSSHConfig(arg1) {
  return window['go']['main']['App']['SaveSSHConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SplitPane(arg1) {
  return window['go']['main']['App']['SplitPane'](arg1);
}
