// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {git} from '../models';

export function ClosePane(arg1:string,arg2:string):Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:main.CreateSessionReq):Promise<Record<string, any>>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetDetectedProfiles():Promise<Array<config.Profile>>;

export function GetGitStatus(arg1:string):Promise<git.GitStatusResult>;

export function GetProfiles():Promise<Array<config.Profile>>;

export function GetServerPort():Promise<number>;

export function GetSessions():Promise<Array<any>>;

export function GitPull(arg1:string):Promise<string>;

export function GitPush(arg1:string):Promise<string>;

export function KillServer():Promise<void>;

export function QuitApp():Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveGitPollInterval(arg1:number):Promise<void>;

export function SaveProfile(arg1:config.Profile):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SplitPane(arg1:main.SplitPaneReq):Promise<Record<string, any>>;
